apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-welocal-dns
  namespace: prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bazihassan@gmail.com
    privateKeySecretRef:
      name: letsencrypt-welocal-dns
    solvers:
    - dns01:
        cnameStrategy: Follow
        digitalocean:
          tokenSecretRef:
            name: welocal-digitalocean-dns
            key: access-token